export const GET_ACCOUNTS = 'getAccounts';
export const GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS';
export const GET_ACCOUNTS_ERROR = 'GET_ACCOUNTS_ERROR';

export const GET_BALANCE = 'getBalance';
export const GET_BALANCE_SUCCESS = 'GET_BALANCE_SUCCESS';
export const GET_BALANCE_ERROR = 'GET_BALANCE_ERROR';
export const ACCOUNT_BALANCE_REQUESTED = 'ACCOUNT_BALANCE_REQUESTED';
