export const SEND_TRANSACTION = 'sendTransaction';
export const SEND_TRANSACTION_SUCCESS = 'SEND_TRANSACTION_SUCCESS';
export const SEND_TRANSACTION_ERROR = 'SEND_TRANSACTION_ERROR';
export const SEND_TRANSACTION_REQUESTED = 'SEND_TRANSACTION_REQUESTED';
